Upgrade EqualsVerifier dependency to version 3.19.4.
Providing Java 21 forward compatibility (#765; see below).

--------

* JDK 21:

HashValueTest > shouldSatisfyEqualsContract() FAILED
    java.lang.AssertionError: EqualsVerifier found a problem in class org.metafacture.metafix.Value$Hash.
    -> Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 18 (62) - update Byte Buddy or set net.bytebuddy.experimental as a VM property

    For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
        at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:315)
        at org.metafacture.metafix.HashValueTest.shouldSatisfyEqualsContract(HashValueTest.java:49)

        Caused by:
        java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 18 (62) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
            at nl.jqno.equalsverifier.internal.lib.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96)
            at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default.parse(TypePool.java:855)
            at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:841)
            at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$AbstractBase.describe(TypePool.java:574)
            at nl.jqno.equalsverifier.internal.lib.bytebuddy.pool.TypePool$AbstractBase$Hierarchical.describe(TypePool.java:657)
            at nl.jqno.equalsverifier.internal.reflection.annotations.AnnotationCacheBuilder.build(AnnotationCacheBuilder.java:39)
            at nl.jqno.equalsverifier.internal.util.Configuration.buildAnnotationCache(Configuration.java:130)
            at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:90)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:380)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:366)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:311)
            ... 1 more

* EqualsVerifier 3.15:

HashValueTest > shouldSatisfyEqualsContract() FAILED
    java.lang.AssertionError: EqualsVerifier found a problem in class org.metafacture.metafix.Value$Hash.
    -> Unable to make field private int[] java.util.regex.IntHashSet.entries accessible: module java.base does not "opens java.util.regex" to unnamed module @74287ea3

    For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
    (EqualsVerifier 3.15, JDK 21.0.11 on Linux)
        at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:351)
        at org.metafacture.metafix.HashValueTest.shouldSatisfyEqualsContract(HashValueTest.java:49)

        Caused by:
        java.lang.reflect.InaccessibleObjectException: Unable to make field private int[] java.util.regex.IntHashSet.entries accessible: module java.base does not "opens java.util.regex" to unnamed module @74287ea3
            at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
            at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
            at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
            at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
            at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:112)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
            at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
            at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:188)
            at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:177)
            at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveInstances(FallbackFactory.java:95)
            at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:40)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:157)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:140)
            at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveArrayInstances(FallbackFactory.java:66)
            at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:36)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:157)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:140)
            at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.traverseFields(FallbackFactory.java:88)
            at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:39)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:157)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:140)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveTuple(PrefabValues.java:81)
            at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:104)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:97)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.wrappedChange(FieldModifier.java:118)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:113)
            at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$1(Rethrow.java:51)
            at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:34)
            at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:49)
            at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:59)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:113)
            at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:100)
            at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:52)
            at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:188)
            at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:177)
            at nl.jqno.equalsverifier.internal.util.Configuration.ensureUnequalExamples(Configuration.java:219)
            at nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:114)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:424)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:410)
            at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:347)
            ... 1 more

* EqualsVerifier 3.16:

HashValueTest > shouldSatisfyEqualsContract() FAILED
    java.lang.AssertionError: EqualsVerifier found a problem in class org.metafacture.metafix.Value$Hash.
    -> Field patternMatcher of type java.util.regex.Matcher is not accessible via the Java Module System.
    Consider opening the module that contains it, or add prefab values for type java.util.regex.Matcher.

    For more information, go to: https://www.jqno.nl/equalsverifier/errormessages
    (EqualsVerifier 3.16, JDK 21.0.11 on Linux)
        at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:349)
        at org.metafacture.metafix.HashValueTest.shouldSatisfyEqualsContract(HashValueTest.java:49)

        Caused by:
        nl.jqno.equalsverifier.internal.exceptions.ModuleException
            at app//nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.handleInaccessibleObjectException(InPlaceObjectAccessor.java:108)
            at app//nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scrambleInternal(InPlaceObjectAccessor.java:82)
            at app//nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:58)
            at app//nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:225)
            at app//nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:210)
            at app//nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:186)
            at app//nl.jqno.equalsverifier.internal.util.Configuration.ensureUnequalExamples(Configuration.java:219)
            at app//nl.jqno.equalsverifier.internal.util.Configuration.build(Configuration.java:114)
            at app//nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.buildConfig(SingleTypeEqualsVerifierApi.java:424)
            at app//nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:410)
            at app//nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:347)
            ... 1 more

            Caused by:
            java.lang.reflect.InaccessibleObjectException: Unable to make field private int[] java.util.regex.IntHashSet.entries accessible: module java.base does not "opens java.util.regex" to unnamed module @74287ea3
                at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
                at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
                at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
                at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
                at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:134)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:122)
                at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scrambleInternal(InPlaceObjectAccessor.java:80)
                at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scramble(InPlaceObjectAccessor.java:58)
                at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedAccessor(ClassAccessor.java:225)
                at nl.jqno.equalsverifier.internal.reflection.ClassAccessor.getRedObject(ClassAccessor.java:199)
                at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveInstances(FallbackFactory.java:99)
                at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:40)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:179)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:162)
                at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.giveArrayInstances(FallbackFactory.java:66)
                at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:36)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:179)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:162)
                at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.traverseFields(FallbackFactory.java:88)
                at nl.jqno.equalsverifier.internal.prefabvalues.factories.FallbackFactory.createValues(FallbackFactory.java:39)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.createTuple(PrefabValues.java:179)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.realizeCacheFor(PrefabValues.java:162)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveTuple(PrefabValues.java:93)
                at nl.jqno.equalsverifier.internal.prefabvalues.PrefabValues.giveOther(PrefabValues.java:130)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$changeField$2(FieldModifier.java:119)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.wrappedChange(FieldModifier.java:140)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.lambda$change$3(FieldModifier.java:135)
                at nl.jqno.equalsverifier.internal.util.Rethrow.lambda$rethrow$1(Rethrow.java:51)
                at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:34)
                at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:49)
                at nl.jqno.equalsverifier.internal.util.Rethrow.rethrow(Rethrow.java:59)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.change(FieldModifier.java:135)
                at nl.jqno.equalsverifier.internal.reflection.FieldModifier.changeField(FieldModifier.java:122)
                at nl.jqno.equalsverifier.internal.reflection.InPlaceObjectAccessor.scrambleInternal(InPlaceObjectAccessor.java:80)
                ... 10 more

HashValueTest > shouldSatisfyEqualsContract() STANDARD_ERROR
    WARNING: A Java agent has been loaded dynamically ([...]/byte-buddy-agent-1.12.19.jar)
    WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
    WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
    WARNING: Dynamic loading of agents will be disallowed by default in a future release