Include Nashorn Javascript engine as standalone library.
Providing Java 21 forward compatibility (#765; JDK 15: Remove the Nashorn JavaScript Engine [JEP 372]).

See also: https://github.com/szegedi/nashorn/wiki/Using-Nashorn-with-different-Java-versions

--------

* JDK 21:

ScriptTest > shouldExecuteJavascriptFunctions FAILED
    org.metafacture.metamorph.MetamorphException: Error while building the Metamorph transformation pipeline: Cannot set file on class Script
        at app//org.metafacture.metamorph.Metamorph.buildPipeline(Metamorph.java:303)
        at app//org.metafacture.metamorph.Metamorph.<init>(Metamorph.java:293)
        at app//org.metafacture.metamorph.Metamorph.<init>(Metamorph.java:269)
        at app//org.metafacture.metamorph.Metamorph.<init>(Metamorph.java:258)
        at app//org.metafacture.metamorph.InlineMorph.create(InlineMorph.java:147)
        at app//org.metafacture.metamorph.InlineMorph.createConnectedTo(InlineMorph.java:187)
        at app//org.metafacture.metamorph.TestHelpers.assertMorph(TestHelpers.java:45)
        at app//org.metafacture.metamorph.TestHelpers.assertMorph(TestHelpers.java:41)
        at app//org.metafacture.metamorph.functions.ScriptTest.shouldExecuteJavascriptFunctions(ScriptTest.java:47)

        Caused by:
        org.metafacture.commons.reflection.ReflectionException: Cannot set file on class Script
            at app//org.metafacture.commons.reflection.ConfigurableClass.applySetters(ConfigurableClass.java:195)
            at app//org.metafacture.commons.reflection.ConfigurableClass.newInstance(ConfigurableClass.java:145)
            at app//org.metafacture.commons.reflection.ObjectFactory.newInstance(ObjectFactory.java:105)
            at app//org.metafacture.metamorph.MorphBuilder.handleFunction(MorphBuilder.java:325)
            at app//org.metafacture.metamorph.AbstractMetamorphDomWalker.handlePostprocess(AbstractMetamorphDomWalker.java:289)
            at app//org.metafacture.metamorph.AbstractMetamorphDomWalker.handleRule(AbstractMetamorphDomWalker.java:268)
            at app//org.metafacture.metamorph.AbstractMetamorphDomWalker.handleRules(AbstractMetamorphDomWalker.java:238)
            at app//org.metafacture.metamorph.AbstractMetamorphDomWalker.walk(AbstractMetamorphDomWalker.java:152)
            at app//org.metafacture.metamorph.AbstractMetamorphDomWalker.walk(AbstractMetamorphDomWalker.java:126)
            at app//org.metafacture.metamorph.AbstractMetamorphDomWalker.walk(AbstractMetamorphDomWalker.java:117)
            at app//org.metafacture.metamorph.Metamorph.buildPipeline(Metamorph.java:300)
            ... 8 more

            Caused by:
            java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
                at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                at org.metafacture.commons.reflection.ConfigurableClass.applySetters(ConfigurableClass.java:191)
                ... 18 more

                Caused by:
                java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(java.io.Reader)" because "engine" is null
                    at org.metafacture.metamorph.functions.Script.setFile(Script.java:66)
                    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
                    ... 20 more