Fix flux.bat for running on Windows
Running flux.bat on Windows failed with a
java.lang.ClassNotFoundException: $FLUX_JAVA_OPTIONS

As the comment above the changed line mentions, the space is
important. Seems it was accidentally removed when reformatting
the file in 3e7f486f5f826a349b0773395dc1be7a8af26ccd